---
title: "Planificación"
slug: schedule
---


|      |  <i class="fas fa-chalkboard-teacher"></i>  Contenidos     |  <i class="fas fa-user-edit"></i>  Prácticas y evaluaciones | <i class="fas fa-book-reader"></i> Lecturas y links
- |-----------|-----------|----------
<font color="orange"> **Agosto** </font> |   |   |
3 | [**1. Presentación**](/class/01-class) <br> - Programa y forma  de trabajo <br/> - La crisis de la ciencia cerrada  | [Película Paywall](https://amara.org/en/videos/nTk5qVME6PP7/es/2350702/)  |  [Nosek, B. A. et al (2015). Promoting an open research culture. Science, 348(6242), 1422–1425.](https://doi.org/10.1126/science.aab2374)
10  | [**2. Antecedentes**](/class/02-class) <br> • principios <br> • problemas <br> • alternativas  | - Inscripción grupos de trabajo  |  [Nassi-Calo (2014) La reproducibilidad en los resultados de investigación](http://blog.scielo.org/es/2014/02/27/la-reproducibilidad-en-los-resultados-de-investigacion-la-punta-del-iceberg/) <br> <br> [Fardella et al (2020) Escribir papers bajo el régimen del management académico: Cuerpo, afectos y estrategias](/docs/fardella2020escribirpapers.pdf) <br><br> [Christensen et al cap2: What is ethical research?](/docs/CAP2 Christensen et al (2019) Transparent and Reproducible Social Science Research.pdf)
17  | [**3. Pre-registros**]()  |    |  [García-Garzón et al (2018) Estudios de replicación, pre-registros y ciencia abierta en Psicología](/docs/ciencia_abierta_psicologia.pdf) <br><br> [Yamada 2018 How to Crack Pre-registration](https://www.frontiersin.org/articles/10.3389/fpsyg.2018.01831/full)
24  | [**4. Datos Abiertos**]()  |   |
31  | [**Asesorías informe 1: Pre-registro y selección de datos**](/programa/#entrega-1-20-pre-registro-y-descripción-de-datos)  | <font color="red"> **Viernes 3: Entrega informe 1** </font>   |
<font color="orange"> **SEPTIEMBRE** </font> |   |   |
7  | [**5. Introducción a la escritura y citas en texto plano**](/class/05-class)   | [Práctica Markdown y Zotero](/assignment/02-code)  | [Healey (2019) The Plain Person’s Guide to Plain Text Social Science](https://plain-text.co/) <br> <br>[Introducción a Markdown](http://rusersgroup.com/blog/rmarkdown) <br> [Capítulo Lenguaje reproducible, secciones 1.1 y 1.2, libro Investigación Social Abierta](https://juancarloscastillo.github.io/in-socabi/lenguaje-reproducible.html) <br> [Zotero](https://www.zotero.org/)
14 | Vacaciones Fiestas Patrias
21 | [**6. Documentos dinámicos**](/slides/06-rmarkdown/06_rmarkdown.html)  | [Práctica RMarkdown/Knitr]()  | [Bowers & Voors (2016) How to improve your relationship with your future self](https://scielo.conicyt.cl/pdf/revcipol/v36n3/art11.pdf)<br><br> [Hoja referencia Rmarkdown](https://rstudio.com/wp-content/uploads/2015/03/rmarkdown-spanish.pdf)
28 | [**7. Flujo de trabajo reproducible / Protocolo IPO**](/class/07-class)  |   | [IPO](https://juancarloscastillo.github.io/ipo/) <br> [TIER](https://www.projecttier.org/)
<font color="orange"> **OCTUBRE** </font> |   |   |
05  | [Asesorías informe 2: Reporte dinámico reproducible](/programa/#entrega-2-30-reporte-dinámico-reproduciblee)  | <font color="red"> ~~**Viernes 8: Entrega informe 2**~~ </font>   |
12 | Semana de Receso ||
19 | PARO  |   |   |
26 | [**8. Control de versiones 1: Git**](/class/08-class)   | Práctica Git <br> **Viernes 29: Entrega informe 2**    | [Git](https://git-scm.com/)
<font color="orange"> **Noviembre** </font> |   |   |
02 | [**9. Control de versiones 2: Github**](/class/09-class)  | Práctica Gihub  <br>  |[Github](https://github.com/)
09  | Semana de receso  |   |
16 | [**10. Acceso y publicación 1**](/class/10-class)  | [OSF](https://osf.io/) y [Pre-prints/Socarxiv](https://socopen.org/)  |  |
23 | [**11. Acceso y publicación 2**](/class/11-class)  |   | [Github pages](https://pages.github.com/) <br> [blogdown](https://bookdown.org/yihui/blogdown/) <br> [Xaringan](https://slides.yihui.org/xaringan/#1)
30 | [Asesoría Informe 3: Proyecto Abierto](/programa/#entrega-3-50-proyecto-abierto) | <font color="red"> **Viernes 03 Dic: Entrega informe 3** </font>
