---
title: Trabajos
slug: trabajos
citeproc: true
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
      toc: TRUE
---


[^courseinfo]: {-}
  `r blogdown::shortcode("courseinfo")`


## Entregas

La evaluación consistirá en la elaboración de un reporte en el formato de artículo de investigación, elaborado en tres entregas parciales en las que se avanza secuencialmente en los contenidos del curso. Estas entregas son grupales, máximo 5 integrantes.

Las fechas de entrega de los trabajos se encuentran en la [pestaña de planificación](/schedule/)

### Entrega 1 (20%): Pre-registro y descripción de datos

Informe que pre-registra la investigación en base a una plantilla. Además, se debe realizar una descripción acabada de los datos a utilizar evaluando su nivel de apertura y documentación, y proponiendo estrategias para compensar deficiencias. Se trabajará en base a datos secundarios (existentes).

Opciones:

- elaboración en base a trabajo previo de otro curso

- estudio de reproducibilidad: elegir una investigación/artículo y reproducir los resultados

- temas de interés general del grupo vinculado a datos existentes que se puedan analizar


Producto a entregar (en archivo pdf):

- inscripción de pre-registro de investigación en plantilla OSF, se sugiere [AsPredicted](https://osf.io/gnxav/) (ver [sesion 3](/class/03-class/)). Se pueden revisar ejemplos de pre-registro de investigaciones (Ej: [aquí](https://osf.io/fazdx)).

  - la plantilla de As.Predicted consiste en una serie de campos que se deben ir completando en el pre-registro. También existe la opción de seleccionar **open ended** en lugar de AsPredicted, lo que permite adjuntar un documento pdf con la información basado en un word como el que está [aquí](https://docs.google.com/document/d/13FFwD_UNUyA4O0iOGyy66_EViN1LkkM4QT_iiUiOwEE/edit). En el caso de utilizar esta plantilla, en la sección de "conditions" se pueden especificar las variables independientes, y en "other" la evaluación de la apertura de los datos (ver abajo)

  - Otros posibles formatos y sus correspondientes plantillas en word se encuentran [aquí](https://osf.io/zab38/wiki/home/)

  - si se opta por Open Ended también se puede considerar otra plantilla que es más apropiada para el trabajo con datos secundarios, como la [Preregistration template for the preregistration of analyses of preexisting data](https://osf.io/p26rq/)

- en la descripción de los datos señalar su nivel de apertura y documentación según los criterios que se señalan en la [sesión 4](/class/03-class/), tomando como referencia aquellos referidos a los estándares [FAIR](https://www.go-fair.org/fair-principles/) y también las indicaciones de [LISA](https://lisa-coes.netlify.app/02componentes/) para apertura de datos.


### Entrega 2 (30%): Reporte dinámico reproducible

Documentación de la investigación en un reporte dinámico basado en un flujo reproducible (Protocolo IPO).

La estructura del trabajo es secundaria, pero se recomienda seguir las secciones habituales (Resumen, Introducción, Antecedentes conceptuales/empíricos, Metodología, Análisis, Conclusiones).

Requisitos:

- utilizar de fuentes bibliográficas en formato Bibtex
- utilizar formato markdown: estructura de títulos, uso de url links, insertar imágenes/tablas
- producción e incorporación de al menos una tabla y un gráfico
- se privilegia salida a html, pero también está la opción de pdf. Lo importante es que ambos sean producidos desde un Rmarkdown


Se debe entregar la carpeta autocontenida del proyecto en formato IPO.

### Entrega 3: (50%): Proyecto Abierto

Desarrollo de repositorio abierto y publicación en formato web y/o OSF-pre-print.

## Requisitos de aprobación

Nota mínima de aprobación: 4,0 (en escala de 1 a 7).

## Palabras clave

Ciencia abierta, reproducibilidad, acceso abierto, transparencia, pre-prints, repositorios, control de versiones, markdown.


## Grupos de trabajo


<iframe src="https://docs.google.com/spreadsheets/d/1-YFRtO0sSKKPyuVzvi4Q1Lpk1li2z5rlJkORZi7VcZ0/edit?usp=sharing" width="1000" height="1000"></iframe>
